logging.level.org.springframework=info
logging.level.com.cognizant=debug
logging.level.org.hibernate.SQL=trace
logging.pattern.console=%d{dd-MM-yy} %d{HH:mm:ss.SSS} %-20.20thread %5p %-25.25logger{25} %25M %4L %m%n

# Switched to H2 Configuration
spring.datasource.url=jdbc:h2:mem:ormlearn;INIT=CREATE TABLE IF NOT EXISTS country(code VARCHAR(2) PRIMARY KEY, name VARCHAR(50))\\;INSERT INTO country VALUES ('IN', 'India')\\;INSERT INTO country VALUES ('US', 'United States of America');
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
